/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/not-found`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/user/users`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useExitAppConfirmation`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/admin/chat-list`; params?: Router.UnknownInputParams; } | { pathname: `/admin/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/admin/profile`; params?: Router.UnknownInputParams; } | { pathname: `/admin/users`; params?: Router.UnknownInputParams; } | { pathname: `/user/chat-list`; params?: Router.UnknownInputParams; } | { pathname: `/user/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/user/edit-profile`; params?: Router.UnknownInputParams; } | { pathname: `/user/profile`; params?: Router.UnknownInputParams; } | { pathname: `/admin/chat/[chatId]`, params: Router.UnknownInputParams & { chatId: string | number; } } | { pathname: `/user/chat/[chatId]`, params: Router.UnknownInputParams & { chatId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/not-found`; params?: Router.UnknownOutputParams; } | { pathname: `/register`; params?: Router.UnknownOutputParams; } | { pathname: `/user/users`; params?: Router.UnknownOutputParams; } | { pathname: `/../hooks/useExitAppConfirmation`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/chat-list`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/users`; params?: Router.UnknownOutputParams; } | { pathname: `/user/chat-list`; params?: Router.UnknownOutputParams; } | { pathname: `/user/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/user/edit-profile`; params?: Router.UnknownOutputParams; } | { pathname: `/user/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/chat/[chatId]`, params: Router.UnknownOutputParams & { chatId: string; } } | { pathname: `/user/chat/[chatId]`, params: Router.UnknownOutputParams & { chatId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/not-found${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `/user/users${`?${string}` | `#${string}` | ''}` | `/../hooks/useExitAppConfirmation${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/admin/chat-list${`?${string}` | `#${string}` | ''}` | `/admin/dashboard${`?${string}` | `#${string}` | ''}` | `/admin/profile${`?${string}` | `#${string}` | ''}` | `/admin/users${`?${string}` | `#${string}` | ''}` | `/user/chat-list${`?${string}` | `#${string}` | ''}` | `/user/dashboard${`?${string}` | `#${string}` | ''}` | `/user/edit-profile${`?${string}` | `#${string}` | ''}` | `/user/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/not-found`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/user/users`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useExitAppConfirmation`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/admin/chat-list`; params?: Router.UnknownInputParams; } | { pathname: `/admin/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/admin/profile`; params?: Router.UnknownInputParams; } | { pathname: `/admin/users`; params?: Router.UnknownInputParams; } | { pathname: `/user/chat-list`; params?: Router.UnknownInputParams; } | { pathname: `/user/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/user/edit-profile`; params?: Router.UnknownInputParams; } | { pathname: `/user/profile`; params?: Router.UnknownInputParams; } | `/admin/chat/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/user/chat/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/admin/chat/[chatId]`, params: Router.UnknownInputParams & { chatId: string | number; } } | { pathname: `/user/chat/[chatId]`, params: Router.UnknownInputParams & { chatId: string | number; } };
    }
  }
}
